name: 'Delete all Release Assets'
description: 'Delete all Release Assets.'
author: 'Jeff King'
inputs:
  release_id:
    description: 'Release ID'
    required: true
runs:
  using: 'node12'
  main: 'index.js'